"""adding initial values for tables

Revision ID: d54ab364e023
Revises: 04da69b17889
Create Date: 2025-12-26 16:01:10.670703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d54ab364e023"
down_revision: Union[str, Sequence[str], None] = "04da69b17889"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO currency (code, name, symbol, is_active) VALUES
        ('USD', 'US Dollar',        '$',   true),
        ('EUR', 'Euro',             '€',   true),
        ('GBP', 'British Pound',    '£',   true),
        ('UAH', 'Ukrainian Hryvnia','₴',   true),
        ('PLN', 'Polish Złoty',     'zł',  true),
        ('JPY', 'Japanese Yen',     '¥',   true),
        ('CAD', 'Canadian Dollar',  'C$',  true),
        ('CHF', 'Swiss Franc',      'Fr',  true)
    """)

    op.execute("""
        INSERT INTO expenses_category (category_name) VALUES
        ('Food & Groceries'),
        ('Transportation'),
        ('Housing & Utilities'),
        ('Entertainment'),
        ('Health'),
        ('Education'),
        ('Shopping'),
        ('Travel'),
        ('Other')

    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
